### ISSUE TITLE
Getting error after connected with social network (fb and google_plus) on WP8

### ISSUE THREAD

**Issue by visnupriya** [nraboy/ng-cordova-oauth#25]
I am getting error as shown below after login with fb or gplus social network. Please help. How to resolve that issue. It is getting on WP8 device only same code works fine on Android and iPhone. Please help me to solve this problem.

```javascript
ERROR:TypeError: Unable to get property 'addEventListener' of undefined or null reference
   at google (x-wmapp0:www/js/ng-cordova.js:2829:11)
   at $scope.connectToGP (x-wmapp0:www/js/controllers.js:426:5)
   at Anonymous function (x-wmapp0:www/js/angular.min.js:177:56)
   at Anonymous function (x-wmapp0:www/js/angular-touch.js:419:9)
   at k.prototype.$eval (x-wmapp0:www/js/angular.min.js:112:57)
   at k.prototype.$apply (x-wmapp0:www/js/angular.min.js:112:322)
   at Anonymous function (x-wmapp0:www/js/angular-touch.js:418:7)
   at b.event.dispatch (x-wmapp0:www/js/lib/jquery.min.js:3:28281)
   at v.handle (x-wmapp0:www/js/lib/jquery.min.js:3:24972)
CordovaBrowser_LoadCompleted
A first chance exception of type 'System.SystemException' occurred in Microsoft.Phone.Interop.ni.dll
Error calling js to fire nativeReady event. Did you include cordova.js in your html script tag?

CordovaBrowser_NavigationFailed :: https://accounts.google.com/o/oauth2/approval?hd=gmail.com&as=3fxxxxxx85797c2e&hl=en_GB&pageId=none&xsrfsign=APsBzxxxxxxAVL0BVElnqr8hP67xxxxxxxxxxTzSrVPG

**Comment by nraboy** [comment]
A few possible reasons for this:

1. Windows Phone is not supported with Ionic Framework.  With that said, I assume you are going to get a mess of errors.
2. The error lists `x-wmapp0` which leads me to believe you're launching some kind of locally hosted server to test.  Mobile apps need to be tested on the device with a built binary file.

The error is claiming to be related to cordova.js which has nothing to do with `$cordovaOauth`.

My conclusion is this is a WP8 compatibility problem.

Regards,
